---Blitz Lua meta file
---@meta
---@class BlitzMcpServerDef
---@field name string
---@field command string
---@field transport? string
---@field args? string[]
---@field tools_prefix? string

---@class BlitzMcp
---Register an MCP stdio server. Disabled until explicitly enabled.
---@field add fun(def: BlitzMcpServerDef): integer
---Enable an MCP server for this session.
---@field enable fun(mcp_id: integer)

---@class BlitzJson
---Encode a Lua value as JSON.
---Supports nil, booleans, numbers, strings, and tables.
---@field encode fun(obj: any): string|nil, boolean
---Decode a JSON string into Lua values.
---JSON arrays become 1-indexed Lua tables; objects become Lua tables; JSON null becomes nil.
---@field decode fun(json: string): any, boolean

---@class BlitzAgentId
---@field index integer
---@field generation integer

---@class BlitzSpawnArgs
---@field parent_id? BlitzAgentId
---@field prompt string
---@field agent_type? integer
---@field fork? boolean

---@class BlitzCmd
---Reset the active session.
---@field reset_session fun()
---Change the working directory.
---@field cd fun(path: string)
---Cancel all in-flight agent work and drop streaming preview.
---@field cancel fun()
---Retry the main agent's last turn.
---@field retry fun()
---Request compaction for the main agent.
---@field compact fun()
---Push a chat entry into the chat log.
---@field push_chat_entry fun(role: string, text: string)
---Queue a user message for the given agent.
---@field queue_agent_message fun(agent_id: BlitzAgentId, text: string)
---Send a user message to the main agent (queued if running, restarted if idle), or start a general agent if none exists.
---@field prompt fun(text: string)
---Reserve a free slot and enqueue a spawn or fork into it.
---@field spawn_agent fun(args: BlitzSpawnArgs): BlitzAgentId|nil
---Block until the referenced agent reaches a terminal state.
---@field await_agent fun(agent_id: BlitzAgentId): integer
---Return the awaited agent's last assistant text.
---@field await_agent_result fun(agent_id: BlitzAgentId): string|nil
---Save current session to disk.
---@field save_session fun(path: string)
---Load a session from disk.
---@field load_session fun(path: string)
---Attach a screenshot/image to the current input.
---@field attach_screenshot fun(data: string, media_type?: string)

---@class BlitzToolDef
---@field BASH string
---@field READ string
---@field VIEW_IMAGE string
---@field WRITE string
---@field EDIT string
---@field PATCH string
---@field AGENT string
---@field ASK string
---@field GLOB string
---@field GREP string
---@field START_MCP string
---@field SKILL string

---@class BlitzEventDef
---Emitted after the active session is reset.
---@field SESSION_RESET integer
---Emitted after an agent slot is created.
---@field AGENT_CREATED integer
---Emitted when an agent starts running.
---@field AGENT_STARTED integer
---Emitted when an agent completes.
---@field AGENT_COMPLETE integer
---Emitted when an agent fails.
---@field AGENT_FAILED integer
---Emitted when an agent is cancelled.
---@field AGENT_CANCELLED integer
---Emitted when compaction starts.
---@field COMPACTION_STARTED integer
---Emitted when compaction completes.
---@field COMPACTION_COMPLETE integer
---Emitted when a tool call starts.
---@field TOOL_CALL_STARTED integer
---Emitted when a tool call completes.
---@field TOOL_CALL_COMPLETE integer
---Emitted when an agent broadcasts a message.
---@field AGENT_BROADCAST integer
---Emitted when a permission request is created.
---@field PERMISSION_REQUESTED integer
---Emitted when a permission request is resolved.
---@field PERMISSION_RESOLVED integer
---Emitted after the user sends a message.
---@field USER_MESSAGE_SENT integer
---Emitted after MCP tools are reloaded.
---@field MCP_TOOLS_RELOADED integer
---Emitted when an agent's system reminder is built. Return a string to append it to the injection.
---@field ON_INJECT integer
---Bind an event listener.
---Example: blitz.events.add_listener(blitz.events.AGENT_COMPLETE, function(agent_id) end)
---@field add_listener fun(event: integer, func: function)

---@class BlitzArgDef
---@field type string
---@field description string
---@field required? boolean

---@class BlitzCtx
---@field cwd string
---@field agent_id BlitzAgentId
---@field state table
---Set the tool status text. May contain ANSI SGR escape codes for styling, and newlines for multiple lines.
---@field set_status fun(msg: string)
---@field set_child_id fun(agent_id: BlitzAgentId)
---@field approve fun(tool_name: string, tool_arguments: string): integer, string|nil
---@field plan fun(path: string, plan_text: string): integer, string|nil
---@field ask fun(header: string, question: string, options: string[]): integer, string|nil

---@class BlitzCall
---@field id string
---@field name string
---@field arguments table

---@class BlitzToolResult
---@field msg? string
---{ media_type = string, data = string }
---@field img? table
---@field exit_loop? boolean

---@class ToolDef
---@field name string
---@field description string
---@field schema? string
---@field args? table<string, BlitzArgDef>
---@field snippet? string
---@field guidelines? string
---@field func fun(ctx: BlitzCtx, call: BlitzCall): BlitzToolResult

---@class BlitzThinking
---@field type string
---@field budget_tokens? integer

---@class BlitzProviderDef
---'openai' | 'response' | 'anthropic' | 'ollama'
---@field type string
---the endpoint url
---@field url string
---the ENVAR holding the api key (not the key itself!)
---@field key_envar string
---@field temperature? number
---@field max_tokens? integer
---@field max_completion_tokens? integer
---@field max_output_tokens? integer
---@field top_p? number
---@field top_k? integer
---@field frequency_penalty? number
---@field presence_penalty? number
---@field enable_thinking? boolean
---@field thinking? BlitzThinking
---requests per minute; 0 = unlimited
---@field rate_limit? integer

---@class BlitzModelCost
---price per 1M input tokens
---@field input number
---price per 1M output tokens
---@field output number
---price per 1M cache-read tokens
---@field cache number

---@class BlitzModelDef
---the API model id
---@field name string
---provider handle from add_provider
---@field provider integer
---model supports images
---@field vision? boolean
---price per 1M tokens; absent = free
---@field cost? BlitzModelCost

---@class BlitzAgentDef
---@field name string
---@field description string
---@field prompt string
---@field tools string[]
---model handle from add_model
---@field model? integer
---@field effort? string
---@field in_agent_tool? boolean

---@class BlitzTokenUsage
---@field input integer
---@field output integer
---@field cache integer
---@field cache_creation integer
---total lifetime cost in USD
---@field cost number

---@class BlitzAppFlags
---@field show_thinking? boolean
---@field debug_log? boolean
---@field skip_permissions? boolean

---@class BlitzTheme
---@field bg? string
---@field overlay_dark? string
---@field overlay? string
---@field muted? string
---@field text? string
---@field ok? string
---@field info? string
---@field warn? string
---@field err? string
---@field on_err? string
---@field diff_surface? string
---@field diff_add? string
---@field diff_remove? string
---@field role_user? string
---@field role_agent? string
---@field role_system? string

---@class BlitzState
---Set a value in the shared state. Pass nil to delete the key.
---Returns true on success, or nil,false on a non-string key or unsupported value type.
---Tables must have a contiguous 1..n array part and string-only keys.
---@field set fun(key: string, value: any)
---Get a value from the shared state. Returns nil if the key is missing,
---or nil,false on a non-string key.
---@field get fun(key: string)

---@class Blitz
---@field mcp BlitzMcp
---@field json BlitzJson
---@field cmd BlitzCmd
---@field tools BlitzToolDef
---@field events BlitzEventDef
---@field AGENT_GENERAL integer
---@field REQ_STATUS_PENDING integer
---@field REQ_STATUS_APPROVED integer
---@field REQ_STATUS_DENIED integer
---@field REQ_STATUS_CHOICE integer
---@field REQ_STATUS_MESSAGE integer
---@field AWAIT_COMPLETE integer
---@field AWAIT_FAILED integer
---@field AWAIT_CANCELED integer
---@field AWAIT_INVALID integer
---Register a tool.
---@field register_tool fun(def: ToolDef): string
---Add a single tool from the tool pool to an agent type's tool set.
---@field add_tool fun(agent_type: integer, tool_name: string)
---Return the main agent, if a session is running.
---@field get_main_agent fun(): BlitzAgentId|nil
---Exit the agent loop with a message.
---@field exit_loop fun(content?: string): BlitzToolResult
---Register a provider.
---@field add_provider fun(def: BlitzProviderDef): integer
---Register a model with provider, vision capability and cost.
---@field add_model fun(def: BlitzModelDef): integer
---Register a complete agent configuration.
---@field add_agent fun(def: BlitzAgentDef): integer
---Set the model config for a specific agent.
---@field set_model_agent fun(agent_type: integer, model: integer, effort?: string)
---Return the model name bound to an agent type.
---@field get_model_name fun(agent_type: integer): string
---Return token usage currently shown by the statusbar.
---@field token_usage fun(): BlitzTokenUsage
---Return main-agent context fill percentage currently shown by the statusbar.
---@field context_percent fun(): number
---Set the default context edge, in tokens, used for statusbar percentage and auto-compaction.
---@field set_compact_edge fun(tokens: integer)
---Bind a vim-style key combo to a Lua callback.
---Examples: "<C-c>", "<M-S-a>", "<Esc>", "<Up>", "<F1>", "a"
---@field bind fun(key: string, func: function)
---Bind a slash command to a Lua callback. The leading "/" is added automatically.
---Example: blitz.add_command("help", function(args) end)
---@field add_command fun(command: string, func: function)
---Override the tool set for a given agent type. Replaces defaults entirely.
---Names must match built-in tool names or names of tools registered via blitz.register_tool.
---@field set_agent_tools fun(agent_type: integer, tool_names: string[])
---Override the system prompt for a given agent type.
---@field set_prompt fun(agent_type: integer, prompt: string)
---Return the current app flags.
---@field get_flags fun(): BlitzAppFlags
---Set the app flags from a table. Missing fields are set to their default values.
---@field set_flags fun(flags: BlitzAppFlags)
---Return the current theme as a table of hex color strings.
---@field get_theme fun(): BlitzTheme
---Set the theme from a table of hex color strings or "transparent". Missing fields keep their current value.
---@field set_theme fun(theme: BlitzTheme)
---Write a debug log line.
---@field log fun(msg: string)
---Execute a shell command.
---@field shell fun(cmd: string): any
---Push a new popup notification with a lifetime of 8s to the top right corner.
---@field push_notification fun(message: string)
---@field state BlitzState

---@type Blitz
blitz = {}
