---Blitz Lua meta file
---@meta
---@class BlitzMcpServerDef
---@field name string
---@field command string
---@field transport? string
---@field args? string[]
---@field tools_prefix? string

---@class BlitzMcp
---Register an MCP stdio server. Disabled until explicitly enabled.
---@field add fun(def: BlitzMcpServerDef): integer
---Enable an MCP server for this session.
---@field enable fun(mcp_id: integer)

---@class BlitzLspServerDef
---@field name string
---@field command string
---@field args? string[]
---@field root? string
---@field language_id? string

---@class BlitzLsp
---Register an LSP stdio server. Disabled until explicitly enabled.
---@field add fun(def: BlitzLspServerDef): integer
---Enable an LSP server for this session.
---@field enable fun(lsp_id: integer)

---@class BlitzJson
---Encode a Lua value as JSON.
---Supports nil, booleans, numbers, strings, and tables.
---@field encode fun(obj: any): string|nil, boolean
---Decode a JSON string into Lua values.
---JSON arrays become 1-indexed Lua tables; objects become Lua tables; JSON null becomes nil.
---@field decode fun(json: string): any, boolean

---@class BlitzAgentId
---@field index integer
---@field generation integer

---@class BlitzSpawnArgs
---@field parent_id? BlitzAgentId
---@field prompt string
---@field agent_type? integer
---@field fork? boolean

---@class BlitzQueue
---Reset the active session.
---@field reset_session fun()
---Cancel all in-flight agent work and drop streaming preview.
---@field cancel fun()
---Retry the main agent's last turn.
---@field retry fun()
---Request compaction for the main agent.
---@field compact fun()
---Switch the active mode. Forces a full mode-reminder on the next turn.
---@field set_mode fun(mode: integer)
---Push a chat entry into the chat log.
---@field push_chat_entry fun(role: string, text: string)
---Queue a user message for the given agent.
---@field queue_agent_message fun(agent_id: BlitzAgentId, text: string)
---Reserve a free slot and enqueue a spawn or fork into it.
---@field spawn_agent fun(args: BlitzSpawnArgs): BlitzAgentId|nil
---Block until the referenced agent reaches a terminal state.
---@field await_agent fun(agent_id: BlitzAgentId): integer
---Return the awaited agent's last assistant text.
---@field await_agent_result fun(agent_id: BlitzAgentId): string|nil
---Save current session to disk.
---@field save_session fun(path: string)
---Load a session from disk.
---@field load_session fun(path: string)
---Attach a screenshot/image to the current input.
---@field attach_screenshot fun(data: string, media_type?: string)

---@class BlitzToolDef
---@field BASH string
---@field CANCEL_BACKGROUND string
---@field READ string
---@field WRITE string
---@field EDIT string
---@field PATCH string
---@field AGENT string
---@field LIST_TASKS string
---@field UPDATE_TASK_STATE string
---@field CREATE_TASK string
---@field ASK string
---@field ENTER_SSH string
---@field EXIT_SSH string
---@field SEND_MESSAGE_TO_AGENT string
---@field AWAIT_AGENT string
---@field CANCEL_AGENT string
---@field RIPGREP string
---@field LOADSKILL string
---@field START_MCP string
---@field START_LSP string
---@field LSP string

---@class BlitzEventDef
---Emitted after the active session is reset.
---@field SESSION_RESET integer
---Emitted after the active session mode changes.
---@field MODE_CHANGED integer
---Emitted after an agent slot is created.
---@field AGENT_CREATED integer
---Emitted when an agent starts running.
---@field AGENT_STARTED integer
---Emitted when an agent completes.
---@field AGENT_COMPLETE integer
---Emitted when an agent fails.
---@field AGENT_FAILED integer
---Emitted when an agent is cancelled.
---@field AGENT_CANCELLED integer
---Emitted when compaction starts.
---@field COMPACTION_STARTED integer
---Emitted when compaction completes.
---@field COMPACTION_COMPLETE integer
---Emitted when a tool call starts.
---@field TOOL_CALL_STARTED integer
---Emitted when a tool call completes.
---@field TOOL_CALL_COMPLETE integer
---Emitted when an agent broadcasts a message.
---@field AGENT_BROADCAST integer
---Emitted when a permission request is created.
---@field PERMISSION_REQUESTED integer
---Emitted when a permission request is resolved.
---@field PERMISSION_RESOLVED integer
---Emitted after the user sends a message.
---@field USER_MESSAGE_SENT integer
---Emitted after MCP tools are reloaded.
---@field MCP_TOOLS_RELOADED integer
---Bind an event listener.
---Example: blitz.events.add_listener(blitz.events.MODE_CHANGED, function(new_mode_id) end)
---@field add_listener fun(event: integer, func: function)

---@class BlitzArgDef
---@field type string
---@field description string
---@field required? boolean

---@class BlitzCtx
---@field cwd string
---@field agent_id BlitzAgentId
---@field state table
---@field set_status fun(msg: string)
---@field set_child_id fun(agent_id: BlitzAgentId)
---@field approve fun(tool_name: string, tool_arguments: string): integer, string|nil
---@field plan fun(path: string, plan_text: string): integer, string|nil
---@field ask fun(header: string, question: string, options: string[]): integer, string|nil

---@class BlitzCall
---@field id string
---@field name string
---@field arguments table

---@class BlitzStatus
---@field status integer
---@field msg? string

---@class ToolDef
---@field name string
---@field description string
---@field schema? string
---@field args? table<string, BlitzArgDef>
---@field func fun(ctx: BlitzCtx, call: BlitzCall): BlitzStatus

---@class BlitzThinking
---@field type string
---@field budget_tokens? integer

---@class BlitzProviderDef
---'openai' | 'anthropic' | 'ollama'
---@field type string
---the endpoint url
---@field url string
---the ENVAR holding the api key (not the key itself!)
---@field key_envar string
---@field effort? string
---@field temperature? number
---@field max_tokens? integer
---@field max_completion_tokens? integer
---@field top_p? number
---@field top_k? integer
---@field frequency_penalty? number
---@field presence_penalty? number
---@field enable_thinking? boolean
---@field thinking? BlitzThinking

---@class BlitzAgentDef
---@field name string
---@field description string
---@field prompt string
---@field tools string[]
---@field model string
---@field effort string
---@field provider integer
---@field in_agent_tool? boolean

---@class BlitzTokenUsage
---@field input integer
---@field output integer
---@field cache integer
---@field cache_creation integer

---@class BlitzAppFlags
---@field show_thinking? boolean
---@field debug_log? boolean
---@field ssh_agent_control? boolean
---@field skip_permissions? boolean

---@class Blitz
---@field mcp BlitzMcp
---@field lsp BlitzLsp
---@field json BlitzJson
---@field queue BlitzQueue
---@field tools BlitzToolDef
---@field events BlitzEventDef
---@field RET_FAILED integer
---@field RET_OK integer
---@field RET_ERR integer
---@field RET_EXIT_LOOP integer
---@field AGENT_GENERAL integer
---@field AGENT_EXPLORE integer
---@field MODE_EXEC integer
---@field REQ_STATUS_PENDING integer
---@field REQ_STATUS_APPROVED integer
---@field REQ_STATUS_DENIED integer
---@field REQ_STATUS_CHOICE integer
---@field REQ_STATUS_MESSAGE integer
---@field AWAIT_COMPLETE integer
---@field AWAIT_FAILED integer
---@field AWAIT_CANCELED integer
---@field AWAIT_INVALID integer
---Register a tool.
---@field register_tool fun(def: ToolDef): string
---Add a single tool from the tool pool to an agent type's tool set.
---@field add_tool fun(agent_type: integer, tool_name: string)
---Return the main agent, if a session is running.
---@field get_main_agent fun(): BlitzAgentId|nil
---Return success with content.
---@field ok fun(content?: string): BlitzStatus
---Return error with message.
---@field err fun(message?: string): BlitzStatus
---Exit the agent loop with a message.
---@field exit_loop fun(content?: string): BlitzStatus
---Register a provider.
---@field add_provider fun(def: BlitzProviderDef): integer
---Register a complete agent configuration.
---@field add_agent fun(def: BlitzAgentDef): integer
---Set the default model.
---@field set_model fun(model: string, handle: integer)
---Set the model config for a specific agent.
---@field set_model_agent fun(agent_type: integer, model: string, effort: string, handle: integer)
---Return token usage currently shown by the statusbar.
---@field token_usage fun(): BlitzTokenUsage
---Return main-agent context fill percentage currently shown by the statusbar.
---@field context_percent fun(): number
---Set the default context edge, in tokens, used for statusbar percentage and auto-compaction.
---@field set_compact_edge fun(tokens: integer)
---Bind a vim-style key combo to a Lua callback.
---Examples: "<C-c>", "<M-S-a>", "<Esc>", "<Up>", "<F1>", "a"
---@field bind fun(key: string, func: function)
---Convert HTML to markdown using the built-in parser.
---@field html_to_markdown fun(html: string): string
---Bind a colon command to a Lua callback.
---Example: blitz.add_command(":help", function(args) end)
---@field add_command fun(command: string, func: function)
---Override the tool set for a given agent type. Replaces defaults entirely.
---Names must match built-in tool names or names of tools registered via blitz.register_tool.
---@field set_agent_tools fun(agent_type: integer, tool_names: string[])
---Override the system prompt for a given agent type.
---@field set_prompt fun(agent_type: integer, prompt: string)
---Override the mode reminder prompt (full variant).
---@field set_mode_prompt fun(mode: integer, prompt: string)
---Override the sparse mode reminder prompt (subsequent turns).
---@field set_mode_prompt_sparse fun(mode: integer, prompt: string)
---Override the display name shown for a mode in the status bar.
---@field set_mode_name fun(mode: integer, name: string)
---Add a custom mode.
---@field add_mode fun(name: string, color: string, prompt: string, sparse: string): integer
---Switch the active session mode. Forces a full mode-reminder on the next turn.
---@field set_mode fun(mode: integer)
---Return the current app flags.
---@field get_flags fun(): BlitzAppFlags
---Set the app flags from a table. Missing fields are set to their default values.
---@field set_flags fun(flags: BlitzAppFlags)
---Write a debug log line.
---@field log fun(msg: string)
---Execute a shell command.
---@field shell fun(cmd: string): any
---Push a new popup notification with a lifetime of 8s to the top right corner.
---@field push_notification fun(message: string)

---@type Blitz
blitz = {}
