---Blitz Lua meta file
---@meta
---@class BlitzMcpServerDef
---@field name string
---@field command string
---@field transport? string
---@field args? string[]
---@field tools_prefix? string

---@class BlitzMcp
---Register an MCP stdio server. Disabled until explicitly enabled.
---@field add fun(def: BlitzMcpServerDef): integer
---Enable an MCP server for this session.
---@field enable fun(mcp_id: integer)

---@class BlitzSshState
---true while tool calls route through ssh
---@field active boolean
---@field user? string
---@field host? string
---remote working directory
---@field cwd? string

---@class BlitzSsh
---Turn ssh routing on. Without a target nothing routes, but auto-approval is still denied.
---@field enable fun()
---Turn ssh routing off. The target stays for re-enable.
---@field disable fun()
---Return the current ssh state. user, host, and cwd are nil without a target;
---the target survives disable.
---@field get_state fun(): BlitzSshState

---@class BlitzJson
---Encode a Lua value as JSON.
---Supports nil, booleans, numbers, strings, and tables.
---@field encode fun(obj: any): string|nil, boolean
---Decode a JSON string into Lua values.
---JSON arrays become 1-indexed Lua tables; objects become Lua tables; JSON null becomes nil.
---@field decode fun(json: string): any, boolean

---@class BlitzBase64
---Encode a binary-safe Lua string as standard padded Base64.
---@field encode fun(data: string): string|nil, boolean
---Decode standard padded Base64 into a binary-safe Lua string.
---@field decode fun(base64: string): string|nil, boolean

---@class BlitzSelectRequest
---very short label shown as a chip
---@field header string
---the question shown above the options
---@field question string
---1-8 option strings; a custom message row is appended when allow_message is on
---@field options string[]
---show the trailing custom message row; default false
---@field allow_message? boolean

---@class BlitzCmd
---Reset the active session.
---@field reset_session fun()
---Change the working directory.
---@field cd fun(path: string)
---Cancel all in-flight agent work and drop streaming preview.
---@field cancel fun()
---Retry the main agent's last turn.
---@field retry fun()
---Compact the main agent now when idle, or before its next turn while running.
---@field compact fun()
---Push a chat entry into the chat log.
---@field message_chat fun(role: string, text: string)
---Send a user message to the main agent (queued if running, restarted if idle), or start a general agent if none exists.
---@field prompt fun(text: string)
---Open a multiple-choice selection (same widget as the ask tool) and return at once. The callback runs with the picked option text and its 1-based index when the user chooses, with (message, nil) for the custom message row when allow_message is on, and with (nil, nil) when canceled.
---@field select fun(request: BlitzSelectRequest, func: fun(choice: string?, index: integer?))
---Attach a screenshot/image to the current input.
---@field attach_screenshot fun(data: string, media_type?: string)

---@class BlitzSpawnArgs
---@field parent_id? integer
---@field prompt string
---@field agent_type? integer
---@field fork? boolean

---@class BlitzAgent
---Reserve a free slot and enqueue a spawn or fork into it.
---@field spawn fun(args: BlitzSpawnArgs): integer|nil
---Queue a user message for the given agent.
---@field message fun(agent_id: integer, text: string)
---Block until the referenced agent reaches a terminal state.
---@field await fun(agent_id: integer): integer
---Return the awaited agent's last assistant text.
---@field result fun(agent_id: integer): string|nil
---Cancel the given agent. Returns 'Success' or 'Not Found'.
---@field cancel fun(agent_id: integer): string
---Cancel a finished or running agent and free its slot. History stays rendered. Returns 'Success' or 'Not Found'.
---@field close fun(agent_id: integer): string

---@class BlitzCmp
---Select the next completion row, like <Tab>. No-op when the popup is closed.
---@field next fun()
---Select the previous completion row, like <C-p>. No-op when the popup is closed.
---@field prev fun()
---Insert the selected completion, like <C-y>. No-op when the popup is closed.
---@field accept fun()

---@class BlitzWidgetBuf
---visible widget width in cells, shrinks when clipped
---@field width integer
---visible widget height in cells, shrinks when clipped
---@field height integer
---write text at widget-relative coords, clipped to the widget rect, theme text color
---@field set fun(x: integer, y: integer, text: string)
---write text with a foreground color
---@field set_color fun(x: integer, y: integer, text: string, color: string)
---solid background fill
---@field fill fun(x: integer, y: integer, w: integer, h: integer, color: string)
---one cell thick background outline
---@field rect fun(x: integer, y: integer, w: integer, h: integer, color: string)
---unicode line border in foreground color
---@field box fun(x: integer, y: integer, w: integer, h: integer, color: string)

---@class BlitzSidebarDef
---'left' (default) or 'right'
---@field side? string
---columns
---@field width integer
---draw callback, runs on every drawn frame
---@field render fun(width: integer, height: integer, buf: BlitzWidgetBuf)

---@class BlitzWidgetHandle
---make the widget visible again
---@field show fun()
---hide the widget, its space returns to the layout
---@field hide fun()
---unregister the widget permanently
---@field remove fun()
---set width (sidebar) or height (panel) in cells
---@field set_size fun(size: integer)

---@class BlitzPanelDef
---rows
---@field height integer
---'between' (default) pins the panel between chat and input, 'below' pins it under the input
---@field place? string
---draw callback, runs on every drawn frame
---@field render fun(width: integer, height: integer, buf: BlitzWidgetBuf)

---@class BlitzDraw
---Reserve a full height sidebar column and draw into it from Lua.
---side is 'left' (default) or 'right', width is cells. A second add on
---the same side replaces the first. The sidebar hides automatically
---while the main column would drop below 40 columns. render runs on
---every drawn frame with widget-relative dimensions and a BlitzWidgetBuf.
---Colors are '#RRGGBB' hex or theme names (bg, muted, text, info, ...).
---@field sidebar fun(def: BlitzSidebarDef): BlitzWidgetHandle
---Reserve a horizontal panel and draw into it from Lua.
---height is cells. Panels of the same place stack bottom up in
---registration order, the first registered panel sits on top of its block.
---place 'between' (default) pins the panel between chat and input,
---place 'below' pins it under the input widget. All panels hide
---automatically while the chat viewport would drop below 6 rows. render
---runs on every drawn frame with widget-relative dimensions and a BlitzWidgetBuf.
---@field panel fun(def: BlitzPanelDef): BlitzWidgetHandle
---Request a UI redraw on the next loop tick. Call from animations to force frames while the app is idle.
---@field redraw fun()

---@class BlitzToolDef
---@field BASH string
---@field READ string
---@field VIEW_IMAGE string
---@field WRITE string
---@field EDIT string
---@field PATCH string
---@field AGENT string
---@field ASK string
---@field GLOB string
---@field GREP string
---@field START_MCP string
---@field SKILL string

---@class BlitzAgentCreatedEvent
---packed AgentId of the new agent
---@field id integer
---agent type name
---@field name string
---nesting depth below the main agent
---@field depth integer

---@class BlitzAgentStartedEvent
---packed AgentId of the agent
---@field id integer
---true on the first run after spawn, false when a queued message or agent result woke the agent
---@field fresh boolean

---@class BlitzAgentEvent
---packed AgentId of the agent
---@field id integer

---@class BlitzAgentFailedEvent
---packed AgentId of the failed agent
---@field id integer
---error name
---@field err string

---@class BlitzUserMessageEvent
---chat text as typed
---@field text string

---@class BlitzPermissionRequestEvent
---hand to blitz.permissions.resolve, or blitz.permissions.get for the full payload
---@field ticket integer

---@class BlitzPermissionPayload
---packed AgentId of the requesting agent
---@field agent_id integer
---@field call_id? string
---call|diff|ask|plan
---@field kind string
---tool name
---@field tool string
---kind == call
---@field description? string
---kind == diff|plan
---@field path? string
---kind == ask
---@field header? string
---kind == ask
---@field question? string
---kind == ask
---@field options? string[]
---kind == plan, plan text
---@field plan? string

---@class BlitzPermissionDecision
---false denies, true approves; on ask picks the recommended option
---@field approved boolean
---deny reason, reaches the model as tool error
---@field msg? string
---1-based option index, ask payloads only; ignored otherwise
---@field select? integer

---@class BlitzHooks
---Register a listener for after the active session is reset. Takes no payload. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field session_reset fun(func: fun())
---Register a listener for after an agent slot is activated. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field agent_created fun(func: fun(ev: BlitzAgentCreatedEvent))
---Register a listener for when an agent starts running; fires on spawn and on every wake-up. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field agent_started fun(func: fun(ev: BlitzAgentStartedEvent))
---Register a listener for when an agent completes. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field agent_complete fun(func: fun(ev: BlitzAgentEvent))
---Register a listener for when an agent run fails. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field agent_failed fun(func: fun(ev: BlitzAgentFailedEvent))
---Register a listener for when an agent is cancelled. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field agent_cancelled fun(func: fun(ev: BlitzAgentEvent))
---Register a listener for when chat compaction starts. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field compaction_started fun(func: fun(ev: BlitzAgentEvent))
---Register a listener for when chat compaction completes. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field compaction_complete fun(func: fun(ev: BlitzAgentEvent))
---Register a listener for after the user sends a message. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field user_message_sent fun(func: fun(ev: BlitzUserMessageEvent))
---Register a listener for after MCP tools are reloaded. Takes no payload. The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field mcp_tools_reloaded fun(func: fun())
---Register a listener for when a tool approval parks for a decision.
---The event carries the ticket; fetch details with
---blitz.permissions.get and decide with blitz.permissions.resolve.
---Unresolved tickets fall back to the TUI.The listener runs in a sandbox Lua VM on a background thread. Cannot mutate lua state. Use `blitz.state.set/get`
---@field permission_requested fun(func: fun(ev: BlitzPermissionRequestEvent))
---Install the system-reminder injection hook. Runs for every agent step
---before the reminder is built, in the main Lua VM on the calling thread.
---Return a string to append it to the agent's <system-reminder> block,
---nil for nothing. Last registration wins. Never call
---blitz.agent.await inside the hook.
---@field inject fun(hook: fun(agent_id: integer): string)
---Install the permission hook. Runs on every tool approval request
---before the approval-mode check, in the main Lua VM on the main
---thread. Return a BlitzPermissionDecision table, or nil for the
---normal flow. Last registration wins. Never call
---blitz.agent.await inside the hook.
---@field approve fun(hook: fun(payload: BlitzPermissionPayload): BlitzPermissionDecision)
---Remove the approve and inject hooks.
---@field clear fun()

---@class BlitzPermissions
---Snapshot every parked approval request as a list of tables: ticket, agent_id, call_id, kind, tool, and the kind fields.
---@field list_pending fun(): table
---Snapshot one parked approval request by ticket, or nil when the ticket is unknown or already resolved.
---@field get fun(ticket: integer): table
---Decide a parked approval request: true when the ticket resolved, false when unknown or already gone. Takes the same BlitzPermissionDecision table as the approve hook. Requests of dead agents deny regardless.
---@field resolve fun(ticket: integer, decision: BlitzPermissionDecision): boolean

---@class BlitzArgDef
---@field type string
---@field description string
---@field required? boolean

---@class BlitzCtx
---@field cwd string
---@field agent_id integer
---@field state table
---Set the tool status text. May contain ANSI SGR escape codes for styling, and newlines for multiple lines.
---@field set_status fun(self: BlitzCtx, msg: string)
---@field set_child_id fun(self: BlitzCtx, agent_id: integer)
---@field approve fun(self: BlitzCtx, description: string): integer, string|nil
---@field plan fun(self: BlitzCtx, path: string, plan_text: string): integer, string|nil
---@field ask fun(self: BlitzCtx, header: string, question: string, options: string[]): integer, string|nil

---@class BlitzCall
---@field id string
---@field name string
---@field arguments table

---@class BlitzToolResult
---@field msg? string
---{ media_type = string, data = string }
---@field img? table
---@field exit_loop? boolean

---@class ToolDef
---@field name string
---@field description string
---@field schema? string
---@field args? table<string, BlitzArgDef>
---@field snippet? string
---@field guidelines? string
---@field func fun(ctx: BlitzCtx, call: BlitzCall): BlitzToolResult

---@class BlitzThinking
---@field type string
---@field budget_tokens? integer

---@class BlitzProviderDef
---'openai' | 'response' | 'anthropic' | 'ollama'
---@field type string
---the endpoint url
---@field url string
---the ENVAR holding the api key (not the key itself!)
---@field key_envar? string
---stored api key; the envar wins when both are set
---@field key? string
---@field temperature? number
---@field max_tokens? integer
---@field max_completion_tokens? integer
---@field max_output_tokens? integer
---@field top_p? number
---@field top_k? integer
---@field frequency_penalty? number
---@field presence_penalty? number
---@field enable_thinking? boolean
---@field thinking? BlitzThinking
---requests per minute; 0 = unlimited
---@field rate_limit? integer

---@class BlitzModelCost
---price per 1M input tokens
---@field input number
---price per 1M output tokens
---@field output number
---price per 1M cache-read tokens
---@field cache number

---@class BlitzModelDef
---the API model id
---@field name string
---provider handle from add_provider
---@field provider integer
---model supports images
---@field vision? boolean
---replay reasoning text as reasoning_content (deepseek/glm style)
---@field replay_reasoning? boolean
---price per 1M tokens; absent = free
---@field cost? BlitzModelCost

---@class BlitzAgentDef
---@field name string
---@field description string
---@field prompt string
---@field tools string[]
---model handle from add_model
---@field model? integer
---@field effort? string
---@field in_agent_tool? boolean

---@class BlitzTokenUsage
---@field input integer
---@field output integer
---@field cache integer
---@field cache_creation integer
---total lifetime cost in USD
---@field cost number

---@class BlitzCapabilityRule
---binary resolved on PATH
---@field binary string
---prompt line added when the binary exists
---@field rule string

---@class BlitzAppFlags
---@field show_thinking? boolean
---@field show_diffs? boolean
---@field debug_log? boolean
---strict|default|yolo|smart
---@field approval_mode? string

---@class BlitzTheme
---@field bg? string
---@field overlay_dark? string
---@field overlay? string
---@field muted? string
---@field text? string
---@field text_hl? string
---@field ok? string
---@field info? string
---@field warn? string
---@field err? string
---@field on_err? string
---@field diff_surface? string
---@field diff_add? string
---@field diff_remove? string
---@field role_user? string
---@field role_agent? string
---@field role_system? string

---@class BlitzShellOpts
---the shell command to run
---@field cmd string
---kill the command after this many seconds
---@field timeout? number
---run on this machine even when SSH routing is active
---@field force_local? boolean

---@class BlitzState
---Set a value in the shared state. Pass nil to delete the key.
---Returns true on success, or nil,false on a non-string key or unsupported value type.
---Tables must have a contiguous 1..n array part and string-only keys.
---@field set fun(key: string, value: any)
---Get a value from the shared state. Returns nil if the key is missing,
---or nil,false on a non-string key.
---@field get fun(key: string)

---@class Blitz
---@field mcp BlitzMcp
---@field ssh BlitzSsh
---@field json BlitzJson
---@field base64 BlitzBase64
---@field cmd BlitzCmd
---@field agent BlitzAgent
---@field cmp BlitzCmp
---@field draw BlitzDraw
---@field tools BlitzToolDef
---@field hooks BlitzHooks
---@field permissions BlitzPermissions
---@field AGENT_GENERAL integer
---@field REQ_STATUS_PENDING integer
---@field REQ_STATUS_APPROVED integer
---@field REQ_STATUS_DENIED integer
---@field REQ_STATUS_CHOICE integer
---@field REQ_STATUS_MESSAGE integer
---@field AWAIT_COMPLETE integer
---@field AWAIT_FAILED integer
---@field AWAIT_CANCELED integer
---@field AWAIT_INVALID integer
---Register a tool.
---@field register_tool fun(def: ToolDef): string
---Add a single tool from the tool pool to an agent type's tool set.
---@field add_tool fun(agent_type: integer, tool_name: string)
---Return the main agent, if a session is running.
---@field get_main_agent fun(): integer|nil
---Exit the agent loop with a message.
---@field exit_loop fun(content?: string): BlitzToolResult
---Register a provider.
---@field add_provider fun(def: BlitzProviderDef): integer
---Register a model with provider, vision capability and cost.
---@field add_model fun(def: BlitzModelDef): integer
---Register a complete agent configuration.
---@field add_agent fun(def: BlitzAgentDef): integer
---Set the model config for a specific agent.
---@field set_agent_model fun(agent_type: integer, model: integer, force?: boolean)
---Set the reasoning effort for an agent type without touching its model.
---@field set_agent_effort fun(agent_type: integer, effort: string, force?: boolean)
---Return the model name bound to an agent type.
---@field get_model_name fun(agent_type: integer): string
---Return the reasoning effort string bound to an agent type.
---@field get_agent_effort fun(agent_type: integer): string
---Return token usage currently shown by the statusbar.
---@field token_usage fun(): BlitzTokenUsage
---Return main-agent context fill percentage currently shown by the statusbar.
---@field context_percent fun(): number
---Set the default context edge, in tokens, used for statusbar percentage and auto-compaction.
---@field set_compact_edge fun(tokens: integer)
---Bind a vim-style key combo to a Lua callback.
---Examples: "<C-c>", "<M-S-a>", "<Esc>", "<Up>", "<F1>", "a"
---
---@field bind fun(key: string, func: fun(), description?: string)
---Bind a slash command to a Lua callback. The leading "/" is added automatically.
---The callback always receives one string: the remaining input after the
---command name, empty when none. Always declare the parameter.
---Example: blitz.add_command("help", function(rem) end)
---
---@field add_command fun(command: string, func: fun(rem: string), description?: string)
---Override the tool set for a given agent type. Replaces defaults entirely.
---Names must match built-in tool names or names of tools registered via blitz.register_tool.
---@field set_agent_tools fun(agent_type: integer, tool_names: string[])
---Register environment capability rules. Each rule names a binary; when it
---resolves through the exec pool, the rule line lands in the injected
---env_capabilities catalogue of agents that own the bash tool. Binaries
---resolve before prompting and follow SSH routing, so the catalogue is
---re-injected whenever the routing changes.
---@field set_capabilities fun(rules: BlitzCapabilityRule[])
---Override the system prompt for a given agent type.
---@field set_prompt fun(agent_type: integer, prompt: string)
---Return the current app flags.
---@field get_flags fun(): BlitzAppFlags
---Set the app flags from a table. Fields you omit are left unchanged.
---@field set_flags fun(flags: BlitzAppFlags)
---Return the current theme as a table of hex color strings.
---@field get_theme fun(): BlitzTheme
---Set the theme from a table of hex color strings or "transparent". Missing fields keep their current value.
---@field set_theme fun(theme: BlitzTheme)
---Write a debug log line.
---@field log fun(msg: string)
---Execute a shell command. Returns output, ok.
---@field shell fun(opts: BlitzShellOpts): any
---Write content to a named file in the active session temp directory and return its path.
---@field write_tempfile fun(name: string, content: string): string
---Push a new popup notification with a lifetime of 8s to the top right corner.
---@field push_notification fun(message: string)
---@field state BlitzState
---Override the status bar text. Return a string to display, or nil to keep the default.
---@field status_bar_render fun(): string|nil

---@type Blitz
blitz = {}
