name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-x64
          - os: macos-latest
            suffix: macos-x64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          cache-size-limit: 4096
      - run: zig build -Doptimize=ReleaseSmall -j1
      - name: rename binary
        run: mv zig-out/bin/blitz zig-out/bin/blitz-${{ matrix.suffix }}
      - name: gzip binary
        run: gzip zig-out/bin/blitz-${{ matrix.suffix }}
      - uses: softprops/action-gh-release@v2
        with:
          files: zig-out/bin/blitz-*